---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dev
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: backend
        image: 203918859979.dkr.ecr.us-east-1.amazonaws.com/auths-2fa-mern-dev-backend:20250310104802-13
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: backend-secret
        ports:
        - containerPort: 8000