apiVersion: v1
data:
  APP_ORIGIN: 
  JWT_EXPIRES_IN: 
  JWT_REFRESH_EXPIRES_IN: 
  JWT_REFRESH_SECRET: 
  JWT_SECRET: 
  MONGO_URI: 
  NODE_ENV: 
  PORT: 
  SMTP_HOST: 
  SMTP_MAIL: 
  SMTP_PASSWORD: 
  SMTP_PORT: 
  SMTP_SERVICE: 
kind: Secret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: dev
