Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    # Specify the box and its version
    jenkins.vm.box = "ubuntu/jammy64"
    jenkins.vm.box_version = "20241002.0.0"

    # Set the hostname
    jenkins.vm.hostname = "jenkins"

    # Configure a private network with a valid IP address
    jenkins.vm.network "private_network", ip: "192.168.56.2"

    # Configure the VM resources (RAM and CPUs)
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "8192" # 8GB RAM
      vb.cpus = 4        # 4 CPUs
    end
  end
end