---
apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: dev
  name: mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels: 
        app: mongodb
    spec: 
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
            name: mongodb-secret
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data/db
      volumes: 
      - name: mongodb-volume
        persistentVolumeClaim:
          claimName: mongodb-volume-claim