---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
  namespace: dev
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db