---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
  namespace: dev
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi