---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: 203918859979.dkr.ecr.us-east-1.amazonaws.com/auths-2fa-mern-frontend
    argocd-image-updater.argoproj.io/payments.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: frontend-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: image.repository
        value: 203918859979.dkr.ecr.us-east-1.amazonaws.com/auths-2fa-mern-frontend
      - name: nameSpace
        value: dev
      - name: image.tag
        value: 0.1.0
      - name: env.viteApiBaseUrl
        value: https://dev.nguyenvietkhoi.io.vn/api/v1
      - name: env.viteGenerateSourcemap
        value: "false"
    path: apps/helm-charts/frontend
    repoURL: git@github.com:viekoi/auths-2fa-mern-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground