---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume-{{ .Values.nameSpace }}
  namespace: {{ .Values.nameSpace }}
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/{{ .Values.nameSpace }}