apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: {{ .Values.nameSpace }}
  annotations:
    cert-manager.io/cluster-issuer: http-01-{{ .Values.nameSpace }}
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.host }}

      secretName: {{ .Values.host }}
