---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-{{ .Values.nameSpace }}
spec:
  acme:
    email: vkhoi444@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-01-{{ .Values.nameSpace }}-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: ingress-nginx