---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.nameSpace }}
  labels:
    role: frontend
spec: 
  replicas: 2
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-regcred
      containers:
      - name: frontend
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: VITE_API_BASE_URL
            value: {{ .Values.env.viteApiBaseUrl }}
          - name: VITE_GENERATE_SOURCEMAP
            value: {{ .Values.env.viteGenerateSourcemap | quote }}
        ports:
        - containerPort: 8080