helm:
  parameters:
  - name: image.repository
    value: 203918859979.dkr.ecr.us-east-1.amazonaws.com/auths-2fa-mern-dev-frontend
    forcestring: false
  - name: nameSpace
    value: dev
    forcestring: false
  - name: image.tag
    value: 0.1.1
    forcestring: true
  - name: env.viteApiBaseUrl
    value: http://localhost:8081/api/v1
    forcestring: false
  - name: env.viteGenerateSourcemap
    value: "false"
    forcestring: false
  - name: image.name
    value: 203918859979.dkr.ecr.us-east-1.amazonaws.com/auths-2fa-mern-dev-frontend
    forcestring: true
