---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: ingress-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: nameSpace
        value: prod
      - name: host
        value: hieubeo.nguyenvietkhoi.io.vn
    path: apps/helm-charts/ingress
    repoURL: git@github.com:viekoi/auths-2fa-mern-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true