---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: 203918859979.dkr.ecr.us-east-1.amazonaws.com/auths-2fa-mern-dev-frontend:20250310110723-3
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: "development"
        ports:
        - containerPort: 8080