apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets
  namespace: {{ .Values.nameSpace }}
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "{{ .Values.nameSpace }}/backend"
        objectType: "secretsmanager"
        jmesPath:
          - path: SMTP_PASSWORD
            objectAlias: SMTP_PASSWORD
          - path: SMTP_MAIL
            objectAlias: SMTP_MAIL
          - path: MONGO_URI
            objectAlias: MONGO_URI
          - path: JWT_SECRET
            objectAlias: JWT_SECRET
          - path: JWT_REFRESH_SECRET
            objectAlias: JWT_REFRESH_SECRET
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: SMTP_PASSWORD
          key: SMTP_PASSWORD
        - objectName: SMTP_MAIL
          key: SMTP_MAIL
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: JWT_REFRESH_SECRET
          key: JWT_REFRESH_SECRET
