apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: database-secrets
  namespace: {{ .Values.nameSpace }}
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "{{ .Values.nameSpace }}/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: MONGO_INITDB_ROOT_USERNAME
            objectAlias: MONGO_INITDB_ROOT_USERNAME
          - path: MONGO_INITDB_ROOT_PASSWORD
            objectAlias: MONGO_INITDB_ROOT_PASSWORD
          - path: MONGO_INITDB_DATABASE
            objectAlias: MONGO_INITDB_DATABASE
  secretObjects:
    - secretName: database-secrets
      type: Opaque
      data:
        - objectName: MONGO_INITDB_ROOT_USERNAME
          key: MONGO_INITDB_ROOT_USERNAME
        - objectName: MONGO_INITDB_ROOT_PASSWORD
          key: MONGO_INITDB_ROOT_PASSWORD
        - objectName: MONGO_INITDB_DATABASE
          key: MONGO_INITDB_DATABASE