---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auths-2fa-mern-secrets
  namespace: {{ .Values.nameSpace }}
spec:
  provider: aws
  parameters:
    region: us-east-1
    usePodIdentity: "true"
    objects: |
      - objectName: dev/backend
        objectType: secretsmanager
        jmesPath:
            - path: SMTP_PASSWORD
              objectAlias: SMTP_PASSWORD
            - path: SMTP_MAIL
              objectAlias: SMTP_MAIL
            - path: MONGO_URI
              objectAlias: MONGO_URI
            - path: JWT_SECRET
              objectAlias: JWT_SECRET
            - path: JWT_REFRESH_SECRET
              objectAlias: JWT_REFRESH_SECRET
      - objectName: dev/database
        objectType: secretsmanager
        jmesPath:
            - path: MONGO_INITDB_ROOT_USERNAME
              objectAlias: MONGO_INITDB_ROOT_USERNAME
            - path: MONGO_INITDB_ROOT_PASSWORD
              objectAlias: MONGO_INITDB_ROOT_PASSWORD
            - path: MONGO_INITDB_DATABASE
              objectAlias: MONGO_INITDB_DATABASE
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: SMTP_PASSWORD
          key: SMTP_PASSWORD
        - objectName: SMTP_MAIL
          key: SMTP_MAIL
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: JWT_REFRESH_SECRET
          key: JWT_REFRESH_SECRET
    - secretName: database-secrets
      type: Opaque
      data:
        - objectName: MONGO_INITDB_ROOT_USERNAME
          key: MONGO_INITDB_ROOT_USERNAME
        - objectName: MONGO_INITDB_ROOT_PASSWORD
          key: MONGO_INITDB_ROOT_PASSWORD
        - objectName: MONGO_INITDB_DATABASE
          key: MONGO_INITDB_DATABASE